blueprint:
  name: "(Vaillant) Notification-Tester"
  description: |
    Utility: Sendet Test-Nachrichten mit exakt derselben Payload-Logik wie die Haupt-Module.

    **Autor:** bananapower | **Version:** v1.0 (Microservices Edition)
  domain: automation
  source_url: https://raw.githubusercontent.com/howtobanana/vaillant-blueprint/main/blueprints/vaillant_notification_tester.yaml
  author: "bananapower"

  input:
    section_test:
      name: "🧪 Test-Auslöser"
      description: |
        Manueller Trigger für den Versand von Test-Benachrichtigungen.
      collapsed: false
      input:
        test_trigger_button:
          name: "Test-Button Helper"
          description: |
            input_button zum Auslösen des Notification-Tests.
          selector:
            entity:
              domain: input_button

    section_notifications:
      name: "📨 Notifications"
      description: |
        Notify-Ziele für Standard- und Critical-Test.
      collapsed: false
      input:
        notify_device:
          name: "Standard Notify Gerät"
          description: |
            Mobile-App Gerät für normale Test-Meldungen.
          default: ""
          selector:
            device:
              filter:
                integration: mobile_app
        critical_notify_device:
          name: "Critical Notify Gerät"
          description: |
            Mobile-App Gerät für kritische Test-Meldungen.
          default: ""
          selector:
            device:
              filter:
                integration: mobile_app

mode: restart

trigger:
  - platform: state
    entity_id: !input test_trigger_button
    id: test_trigger

condition: []

action:
  - variables:
      inputs:
        test_trigger_button: !input test_trigger_button
        notify_device: !input notify_device
        critical_notify_device: !input critical_notify_device
      notify_service: >
        {% if inputs.notify_device is string and inputs.notify_device[:7] == 'notify.' %}
          {{ inputs.notify_device }}
        {% elif inputs.notify_device != '' %}
          {% set user_name = device_attr(inputs.notify_device, 'name_by_user') %}
          {% set dev_name = user_name if (user_name is string and (user_name | trim) != '') else device_attr(inputs.notify_device, 'name') %}
          {% if dev_name is string and (dev_name | trim) != '' %}
            {{ 'notify.mobile_app_' ~ ((dev_name | slugify) | replace('-', '_')) }}
          {% else %}
            ""
          {% endif %}
        {% else %}
          ""
        {% endif %}
      critical_notify_service: >
        {% if inputs.critical_notify_device is string and inputs.critical_notify_device[:7] == 'notify.' %}
          {{ inputs.critical_notify_device }}
        {% elif inputs.critical_notify_device != '' %}
          {% set user_name = device_attr(inputs.critical_notify_device, 'name_by_user') %}
          {% set dev_name = user_name if (user_name is string and (user_name | trim) != '') else device_attr(inputs.critical_notify_device, 'name') %}
          {% if dev_name is string and (dev_name | trim) != '' %}
            {{ 'notify.mobile_app_' ~ ((dev_name | slugify) | replace('-', '_')) }}
          {% else %}
            {{ notify_service }}
          {% endif %}
        {% else %}
          {{ notify_service }}
        {% endif %}

  - service: "{{ notify_service }}"
    data:
      title: "Vaillant v1.0 Test (Info)"
      message: "✅ Dies ist eine normale Info-Nachricht (wie 'Fenster zu')."
    continue_on_error: true

  - service: "{{ critical_notify_service }}"
    data:
      title: "Vaillant v1.0 Test (ALARM)"
      message: "🚨 Dies ist eine KRITISCHE Warnung (wie 'Regen/Offen'). Wenn du das hörst, funktioniert die Ventilation-Config."
      data:
        push:
          interruption-level: critical
          sound:
            name: alarm.caf
            critical: 1
            volume: 1.0
          ttl: 0
          priority: high
    continue_on_error: true
